version: "3.8"
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bookhive_test
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  bookhive:
    build: .
    environment:
      NODE_ENV: test
      MONGODB_URI_TEST: mongodb://mongo:27017/bookhive_test
    depends_on:
      mongo:
        condition: service_healthy
    command: npm test
