version: "3.8"
services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: bookhive_test

  bookhive:
    build: .
    environment:
      NODE_ENV: test
      MONGODB_URI_TEST: mongodb://mongo:27017/bookhive_test
    depends_on:
      - mongo
    command: npm test
