services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  test-runner:
    build: .
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - MONGODB_URI_TEST=mongodb://mongo:27017/bookhive_test
    command: npm test

  bookhive:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/bookhive
    command: npm start
    ports:
      - "3000:3000"
