version: "3.9"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo-test
    ports:
      - "27017:27017"
    networks:
      - bookhive-net

  bookhive:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookhive-test
    depends_on:
      - mongo
    environment:
      - NODE_ENV=test
      - MONGODB_URI_TEST=mongodb://mongo:27017/bookhive_test
      - JWT_SECRET=mystrongsecret
    command: >
      sh -c "npm install &&
             npm test"
    networks:
      - bookhive-net

networks:
  bookhive-net:
    driver: bridge
